In [28]:
%load_ext autoreload
%autoreload 2
from predictor import Predictor

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:
model_name = "models/telegram_multiclass_1"
pred = Predictor(model_name)

messages = [
    "this is very positive for this project",
    "this is great news", 
    "this is good",
    "i am bullish on this project",
    "i am dumping all my coins now!", 
    "time to buy", 
    "time to sell",
    "this is a shit coin",
    "thanks for the info",
    "i am not sure about that",
    "could you provide us more details?"
]

preds, probs  = pred.compute_predictions(messages)

In [30]:
probs

tensor([[0.0026, 0.0093, 0.9880],
        [0.0024, 0.0095, 0.9881],
        [0.0022, 0.0603, 0.9375],
        [0.0087, 0.3346, 0.6567],
        [0.9956, 0.0028, 0.0016],
        [0.0837, 0.8915, 0.0249],
        [0.9640, 0.0329, 0.0031],
        [0.9957, 0.0027, 0.0016],
        [0.0018, 0.9517, 0.0465],
        [0.0148, 0.9841, 0.0010],
        [0.0018, 0.9941, 0.0041]], device='mps:0')

In [31]:
pred.top_negative(messages, probs)

[('this is a shit coin',
  array([0.9957497 , 0.00268228, 0.00156796], dtype=float32)),
 ('i am dumping all my coins now!',
  array([0.99555486, 0.00282821, 0.00161686], dtype=float32)),
 ('time to sell', array([0.9639674 , 0.03294852, 0.00308403], dtype=float32)),
 ('time to buy', array([0.08365349, 0.891461  , 0.02488548], dtype=float32)),
 ('i am not sure about that',
  array([0.01481705, 0.9841474 , 0.00103553], dtype=float32)),
 ('i am bullish on this project',
  array([0.00867337, 0.33461767, 0.6567089 ], dtype=float32)),
 ('this is very positive for this project',
  array([0.00261058, 0.00934156, 0.98804784], dtype=float32)),
 ('this is great news',
  array([0.00236358, 0.00950159, 0.98813486], dtype=float32)),
 ('this is good', array([0.00220504, 0.06030818, 0.93748677], dtype=float32)),
 ('could you provide us more details?',
  array([0.00179174, 0.99408746, 0.00412079], dtype=float32))]

In [32]:
pred.top_positive(messages, probs)

['this is great news',
 'this is very positive for this project',
 'this is good',
 'i am bullish on this project',
 'thanks for the info',
 'time to buy',
 'could you provide us more details?',
 'time to sell',
 'i am dumping all my coins now!',
 'this is a shit coin']

### With telegram real messages

In [45]:
import os
from telethon.sync import TelegramClient
from IPython.display import display

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv()) # read local .env file

api_id = os.environ["TELEGRAM_API_ID"]
api_hash = os.environ["TELEGRAM_API_HASH"]
phone = "+34634454832"
username = "@elvesipeto"
messages = []

client = TelegramClient("../sessions_data/+34634454832", api_id, api_hash)
channel_id = "@runonflux"
channel_messages = []
async with client:
        async for msg in client.iter_messages(channel_id, 2000):
            channel_messages.append(msg.message)

In [34]:
len(channel_messages)

1000

In [49]:
filtered_messages = [m for m in channel_messages if m != None and len(m) > 2]
preds, probs  = pred.compute_predictions(filtered_messages)

In [50]:
negative = pred.top_negative(filtered_messages, probs)

In [51]:
list(negative)

['Why Flux always 0,31$ 🤷\u200d♂',
 "Got banned for forwarding Liza's message about the AMA, asked if it was a mistake because it's from Flux team, they said not allowed 🥲",
 'Don’t listen. That’s fake admin',
 "there's an aktar and a bobby DM me atm - are they scammers or real admin?",
 'Hey mate, see message above you. A scammer tagging a scam duplicate account of you, asking people to DM it',
 'Scammers go fuck yourselfes dont dm me',
 '@iMnOTdAz [1211414389] is sending a spam message. \nAction: Banned 🚷 until 15/10/2023 21:17.',
 '@David_trader54 [6200109690] is sending a spam message. \nAction: Banned 🚷 until 09/10/2023 13:15.',
 'Сергей [5966134763] is sending a spam message. \nAction: Banned 🚷 until 19/10/2023 05:01.',
 'Insufficient funds to pay Polygon Chain transaction\nfee.',
 "If you are getting these NFT's in your wallet do not click on/or interact with them\nThey are a 100% scam trying to rob you",
 'Anybody withdraw Flux  from CoinEX?\nLooks suspended',
 '7th red month s

In [37]:
pred.top_positive(filtered_messages, probs)

['Or is it a total rebuild',
 'I have kda on zelcore on the income wallet but when I want to use it in zelcore fusion its showing 0',
 'Yes, I enabled it. Now I just forget it and want to know how to modify it and get it back.',
 'If you have enabled d2fa pin for login, then of course you need both, your password AND the d2fa pin',
 '📢 FluxOS v4.11.0 has been released!\n\n\nThis release improves the consistency of checks for opened ports.\nFor the full changelog, please refer to:\nhttps://github.com/RunOnFlux/flux/releases/tag/v4.11.0 \n\n\n#Web3 #DePIN #SuperCloud',
 'The #Flux team, doing what they do, making magic!',
 'Q3 2023 has been a massive quarter for Flux and PoUW! ☁️\n\nRead about our roadmap delivery including a record number of exchange listings and other huge milestones in our Q3 recap article here...\nhttps://fluxofficial.medium.com/flux-q3-2023-report-9594d85adb52',
 'Q3 2023 has been a massive quarter for Flux and PoUW! ☁️\n\nRead about our roadmap delivery including a

In [38]:
m = [
    "this is a shit coin",
    '$FLUX is now available on Uphold! Trading is LIVE ✅\n\n☁️ Flux aims to build the next generation of decentralized computing power for Web3. Trade FLUX now: http://wallet.uphold.com/login',
    "this is a clear hodl",
    'Hey how come Bunny analyst revenue has fallen so much... Shows 8.5k flux and we are already past the half way mark of the month... Any reason for such a dip?? Even no. Of apps are falling'
]

preds, probs  = pred.compute_predictions(m)

In [39]:
probs

tensor([[0.9957, 0.0027, 0.0016],
        [0.0019, 0.0095, 0.9886],
        [0.0043, 0.9568, 0.0388],
        [0.9922, 0.0057, 0.0021]], device='mps:0')

In [40]:
prob_np = probs.cpu().numpy()
idx = prob_np[:, 0].argsort()[::-1]
idx

array([0, 3, 2, 1])

In [41]:

most_negative = [(m[i], probs[i]) for i in list(idx)]
most_negative

[('this is a shit coin', tensor([0.9957, 0.0027, 0.0016], device='mps:0')),
 ('Hey how come Bunny analyst revenue has fallen so much... Shows 8.5k flux and we are already past the half way mark of the month... Any reason for such a dip?? Even no. Of apps are falling',
  tensor([0.9922, 0.0057, 0.0021], device='mps:0')),
 ('this is a clear hodl', tensor([0.0043, 0.9568, 0.0388], device='mps:0')),
 ('$FLUX is now available on Uphold! Trading is LIVE ✅\n\n☁️ Flux aims to build the next generation of decentralized computing power for Web3. Trade FLUX now: http://wallet.uphold.com/login',
  tensor([0.0019, 0.0095, 0.9886], device='mps:0'))]

In [42]:
pred.top_negative(m, probs)

[('this is a shit coin',
  array([0.9957497 , 0.00268228, 0.00156796], dtype=float32)),
 ('Hey how come Bunny analyst revenue has fallen so much... Shows 8.5k flux and we are already past the half way mark of the month... Any reason for such a dip?? Even no. Of apps are falling',
  array([0.99221957, 0.00566037, 0.00212005], dtype=float32)),
 ('this is a clear hodl',
  array([0.00433448, 0.95681584, 0.0388497 ], dtype=float32)),
 ('$FLUX is now available on Uphold! Trading is LIVE ✅\n\n☁️ Flux aims to build the next generation of decentralized computing power for Web3. Trade FLUX now: http://wallet.uphold.com/login',
  array([0.00193406, 0.00947078, 0.9885952 ], dtype=float32))]